---
# ============================================================================
# VM Configuration for KVM/Libvirt Ansible Playbooks - CLEAN VERSION
# ============================================================================
# This file contains ONLY user-configurable variables.
# Implementation details are handled by the role.
#
# Usage:
#   - Variables defined here are automatically loaded by all playbooks
#   - Override any values by creating environment-specific files in inventories/{env}/group_vars/
#   - This file is shared across all environments for consistency
#
# ============================================================================

# ============================================================================
# VM CONFIGURATION - User Choices
# ============================================================================
vm_name: hello-vm
vm_memory: 2048 # Memory in MB
vm_vcpus: 1 # Number of virtual CPUs
vm_disk_size: 20 # Disk size in GB for the overlay disk

# ============================================================================
# INFRASTRUCTURE SETTINGS - Environment Specific
# ============================================================================
image_dir: /var/lib/libvirt/images # Standard location for libvirt images
cloud_img_url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
cloud_img_base_name: noble-server-cloudimg-amd64.img

# ============================================================================
# NETWORK CONFIGURATION - User/Environment Specific
# ============================================================================
vm_static_ip: 192.168.122.100 # Static IP for the VM
vm_netmask: 255.255.255.0 # Netmask
vm_gateway: "192.168.122.1" # Gateway for default libvirt network
vm_dns: 8.8.8.8 # DNS server

# ============================================================================
# AUTHENTICATION - User Specific
# ============================================================================
ssh_key_path: "/home/liuyaqiu/code/learn-ansible/ci-artifacts/ansible-vm.pub"
ssh_private_key_path: "/home/liuyaqiu/code/learn-ansible/ci-artifacts/ansible-vm"
cloud_init_user: ubuntu
cloud_init_password: ubuntu # Consider using ansible-vault for production

# ============================================================================
# BEHAVIOR CONFIGURATION - User Preferences
# ============================================================================
confirm_cleanup: false # Set to true to require confirmation before cleanup
wait_for_ssh_timeout: 300 # Seconds to wait for SSH accessibility
cloud_init_check_retries: 30 # Number of times to check cloud-init status
cloud_init_check_delay: 10 # Seconds between cloud-init status checks

# ============================================================================
# PACKAGE LISTS - User/Environment Specific
# ============================================================================
vm_packages:
  - net-tools
  - iputils-ping
  - curl
  - wget
  - git
  - vim
# System packages are defined in role vars (OS-specific knowledge)
