---
# ============================================================================
# Ansible Requirements File
# ============================================================================
# This file specifies external collections and roles required by the project
#
# Install with: ansible-galaxy install -r requirements.yml
# ============================================================================

collections:
  # Core Ansible collections
  - name: ansible.posix
    version: ">=1.5.0"

  # Community collections with version pinning to avoid conflicts
  - name: community.general
    version: ">=8.0.0,<12.0.0"

  # Libvirt management collection
  - name: community.libvirt
    version: ">=1.2.0"

  # Cloud management collections
  - name: community.crypto
    version: ">=2.8.0"

roles:
  # External roles can be added here if needed
  # Example:
  # - name: geerlingguy.docker
  #   version: "4.2.0"
