# ============================================================================
# KVM VM Role - Main Tasks
# ============================================================================

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  failed_when: false

- name: Validate role parameters
  ansible.builtin.include_tasks: validate.yml
  tags: [always, validate]

- name: Setup KVM/Libvirt environment
  ansible.builtin.include_tasks: setup-kvm.yml
  when: kvm_vm_state != 'absent'
  tags: [setup, kvm]

- name: Manage VM lifecycle
  ansible.builtin.include_tasks: "{{ kvm_vm_state }}.yml"
  tags: [vm-lifecycle]

- name: Display VM information
  ansible.builtin.include_tasks: info.yml
  when: kvm_vm_state in ['present', 'running']
  tags: [info]
