galaxy_info:
  role_name: kvmvm
  author: "VM Infrastructure Team"
  description: "Complete KVM virtual machine lifecycle management"
  company: "Learning Ansible"
  license: "MIT"
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - virtualization
    - kvm
    - libvirt
    - cloudinit
    - vmmanagement

dependencies: []
