---
# ============================================================================
# KVM VM Role - Default Variables
# ============================================================================
# These are the default values for the kvm-vm role.
# They can be overridden in group_vars/, host_vars/, or playbook vars.
# ============================================================================

# ============================================================================
# VM CONFIGURATION DEFAULTS
# ============================================================================
kvm_vm_name: "default-vm"
kvm_vm_memory: 2048          # Memory in MB
kvm_vm_vcpus: 1             # Number of virtual CPUs
kvm_vm_disk_size: 20        # Disk size in GB

# ============================================================================
# NETWORK CONFIGURATION DEFAULTS
# ============================================================================
kvm_vm_static_ip: "192.168.122.100"
kvm_vm_netmask: "255.255.255.0"
kvm_vm_dns: "8.8.8.8"
kvm_vm_bridge: "virbr0"

# ============================================================================
# CLOUD IMAGE DEFAULTS
# ============================================================================
kvm_cloud_img_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
kvm_cloud_img_base_name: "noble-server-cloudimg-amd64.img"

# ============================================================================
# AUTHENTICATION DEFAULTS
# ============================================================================
kvm_ssh_key_path: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"          # Public key for cloud-init
kvm_ssh_private_key_path: "{{ ansible_env.HOME }}/.ssh/id_rsa"      # Private key for SSH connections
kvm_cloud_init_user: "ubuntu"
kvm_cloud_init_password: "ubuntu"

# ============================================================================
# BEHAVIOR DEFAULTS
# ============================================================================
kvm_confirm_cleanup: false
kvm_wait_for_ssh_timeout: 300
kvm_cloud_init_check_retries: 30
kvm_cloud_init_check_delay: 10

# ============================================================================
# PACKAGE DEFAULTS
# ============================================================================
kvm_vm_packages:
  - net-tools
  - iputils-ping
  - curl
  - wget
  - git
  - vim

# ============================================================================
# DIRECTORY DEFAULTS
# ============================================================================
kvm_image_dir: "/var/lib/libvirt/images"

# ============================================================================
# ROLE BEHAVIOR FLAGS
# ============================================================================
kvm_vm_state: "present"     # present, absent, running, stopped
kvm_force_recreate: false   # Force VM recreation even if it exists
kvm_skip_cloud_init_wait: false  # Skip waiting for cloud-init completion
